# Generated by Django 4.1.3 on 2023-04-15 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="tag",
            field=models.ManyToManyField(
                null=True, to="blog.posttag", verbose_name="Post tags"
            ),
        ),
    ]
