# Generated by Django 4.1.3 on 2023-04-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_post_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="tag",
            field=models.ManyToManyField(
                blank=True, null=True, to="blog.posttag", verbose_name="Post tags"
            ),
        ),
    ]
