# Generated by Django 4.1.3 on 2023-04-29 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_post_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.SlugField(
                blank=True, default="", editable=False, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="tag",
            field=models.ManyToManyField(
                blank=True, to="blog.posttag", verbose_name="Post tags"
            ),
        ),
    ]
