# Generated by Django 4.1.3 on 2023-04-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_post_slug_alter_post_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(blank=True, editable=False, null=True),
        ),
    ]
