# Generated by Django 4.1.3 on 2023-04-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_remove_post_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.SlugField(blank=True, default="", editable=False, unique=True),
        ),
    ]
