# Generated by Django 4.1.3 on 2023-05-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_post_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30)),
                (
                    "level",
                    models.CharField(
                        choices=[("JR", "Junior"), ("SR", "Senior")],
                        default="JR",
                        max_length=2,
                    ),
                ),
                ("bio", models.TextField()),
            ],
        ),
    ]
