# Generated by Django 4.1.3 on 2023-05-05 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_author"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="author",
            options={"verbose_name": "Author", "verbose_name_plural": "Authors"},
        ),
        migrations.RenameField(
            model_name="author",
            old_name="title",
            new_name="name",
        ),
    ]
