# Generated by Django 4.1.3 on 2023-06-13 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0016_postvisit"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=30)),
                ("content", models.TextField()),
                ("name", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=254)),
            ],
            options={
                "verbose_name": "Post Comment",
                "verbose_name_plural": "Post Comments",
            },
        ),
    ]
