# Generated by Django 4.1.3 on 2023-06-13 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0017_postcomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="postcomment",
            name="create_date",
            field=models.DateField(auto_now_add=True, null=True, verbose_name="Date"),
        ),
        migrations.AddField(
            model_name="postcomment",
            name="post",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="blog.post"
            ),
        ),
    ]
