# Generated by Django 4.1.3 on 2023-06-20 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0018_postcomment_create_date_postcomment_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="postcomment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="blog.postcomment",
            ),
        ),
    ]
