# Generated by Django 4.1.3 on 2022-11-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('color', models.CharField(choices=[('B', 'Black'), ('Y', 'Yellow')], max_length=10)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('price', models.IntegerField()),
                ('description', models.TextField(db_index=True)),
                ('slug', models.SlugField(blank=True, default='', max_length=200, unique=True, verbose_name='slug title')),
                ('is_active', models.BooleanField(default=False, verbose_name='active')),
            ],
        ),
    ]
