# Generated by Django 4.1.3 on 2022-11-23 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_product_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='product_category',
            new_name='ProductCategory',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_category',
            new_name='category',
        ),
    ]
