# Generated by Django 4.1.3 on 2022-11-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_productbrand_options_alter_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('B', 'Black'), ('Y', 'Yellow'), ('W', 'White'), ('A', 'Aqua'), ('G', 'Green'), ('BL', 'Blue')], max_length=10),
        ),
    ]
