# Generated by Django 4.1.3 on 2022-12-29 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_productcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcomment',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
        ),
    ]
