# Generated by Django 4.1.3 on 2022-12-29 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_productcomment_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcomment',
            old_name='post',
            new_name='product',
        ),
    ]
