# Generated by Django 4.1.3 on 2023-01-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_rename_post_productcomment_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcomment',
            name='create_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
